jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  bundler-audit:
    machine: true
    steps:
      - checkout

      - run: docker run --rm -v $(pwd):/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json

      - store_artifacts:
          path: bundle-audit-output.json
          destination: bundler-audit-artifact


workflows:
  version: 2
  rails:
    jobs:
      - build
      - test
      - bundler-audit
      - integration
      - prod
